### PR TITLE
Update to gtest 1.11

### LINKED ISSUE #23: Current Gmock generates a lot of warning on Ubuntu 22.04 with Clang
On Humble building unittests generated a lot of warning with regard to GMock:
```
In file included from /opt/ros/humble/src/gmock_vendor/include/gmock/gmock-spec-builders.h:75:
/opt/ros/humble/src/gmock_vendor/include/gmock/gmock-matchers.h:721:3: warning: definition of implicit copy constructor for 'StrEqualityMatcher<std::basic_string<char>>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(StrEqualityMatcher);
```
Can this be fixed since it generates a lot warning making it impossible to find the error.

In GMock this is fixed in https://github.com/google/googletest/pull/2815

### PR DESCRIPTION
**Pull request by clalancette**
This matches the version that is in Ubuntu 22.04, and it should fix some warnings when building with Clang.

Draft for now while I get some feedback on it.

### CODE REVIEW

**Comment by clalancette** [comment]
CI just to see if things are happy with this:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17607/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12149/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18173/)

**Comment by clalancette** [comment]
Another try:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17846/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12414/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18514/)

**Review by ChrisThrasher — APPROVED** [review]
This updating is holding back MoveIt2 from using `-Wpedantic`. I can confirm that this works and lets us finally enable that warning.

**Comment by clalancette** [comment]
Unfortunately it is still causing CI to be yellow, and I haven't had time to go back and look at why.  If you have some time to look at that and propose possible fixes, that would be helpful.

**Comment by ChrisThrasher** [comment]
https://ci.ros2.org/job/ci_linux/17846/gcc/new/source.3769323b-695d-4413-a06b-0a8173357ff9/#316

The error seems to be that there's some new code in v1.11 that triggers `-Wmaybe-uninitialized`. I think [this was fixed](https://github.com/google/googletest/pull/3797) in v1.12. Because GTest headers should be treated as system headers and thus no warnings get emitted in them, is this something we need to worry about?

**Comment by clalancette** [comment]
> The error seems to be that there's some new code in v1.11 that triggers `-Wmaybe-uninitialized`. I think [this was fixed](https://github.com/google/googletest/pull/3797) in v1.12. Because GTest headers should be treated as system headers and thus no warnings get emitted in them, is this something we need to worry about?

You are right, nowadays we are treating them as system headers, so this probably isn't a problem anymore.

That said, this change is not compiling anymore locally for me.  I had to upgrade a bunch of our packages to C++17 (which we honestly should have done a while ago).  I'm slowly getting those PRs in, but this will take some time.  Once we have those in, I'll rebase this and try CI again.

**Comment by ChrisThrasher** [comment]
> That said, this change is not compiling anymore locally for me. I had to upgrade a bunch of our packages to C++17

Did this update accidentally start using C++17 features? The latest release only claims to require C++14. What specifically fails to compile for you?

**Comment by clalancette** [comment]
> What specifically fails to compile for you?

When I go to compile this PR against the rest of the ROS 2 core, `rcutils` fails to build:

```
$ colcon build --event-handlers console_direct+ --packages-up-to rcutils
...
Starting >>> rcutils
...
/usr/bin/ld: CMakeFiles/test_allocator.dir/test/test_allocator.cpp.o: in function `TestAllocatorFixture_test_default_allocator_normal_Test::TestBody()':
test_allocator.cpp:(.text+0x38c): undefined reference to `osrf_testing_tools_cpp::memory_tools::on_unexpected_malloc(std::variant<std::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::function<void ()>, decltype(nullptr)>)'
/usr/bin/ld: test_allocator.cpp:(.text+0x3c2): undefined reference to `osrf_testing_tools_cpp::memory_tools::on_unexpected_realloc(std::variant<std::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::function<void ()>, decltype(nullptr)>)'
/usr/bin/ld: test_allocator.cpp:(.text+0x3f8): undefined reference to `osrf_testing_tools_cpp::memory_tools::on_unexpected_calloc(std::variant<std::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::function<void ()>, decltype(nullptr)>)'
/usr/bin/ld: test_allocator.cpp:(.text+0x42e): undefined reference to `osrf_testing_tools_cpp::memory_tools::on_unexpected_free(std::variant<std::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::function<void ()>, decltype(nullptr)>)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/test_allocator.dir/build.make:101: test_allocator] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:455: CMakeFiles/test_allocator.dir/all] Error 2
```

**Comment by ChrisThrasher** [comment]
`osrf_testing_tools_cpp` is using `std::variant` from C++17 but isn't specifying that it requires C++17. That may be related to this error you're getting although I'd expect that to manifest at compile time, not link time.

https://github.com/osrf/osrf_testing_tools_cpp/blob/master/osrf_testing_tools_cpp/CMakeLists.txt#L9

**Comment by clalancette** [comment]
OK, we've now updated osrf_testing_tools_cpp to use C++17.  Let's give CI another shot here:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18265/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12801/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18942/)

**Review by cottsay — CHANGES_REQUESTED** [review]
A few things:
1. This needs a rebase or merge to take changes to the package manifest from `rolling`
2. The `CMakeLists.txt.upstream` should be updated within the `googletest` and `googlemock` subdirectories - this appears to have been lost in the merge.
3. The version snapshot list in the package manifests immediately prior to the version number should be updated with the new google/googletest ref

**Comment by cottsay** [comment]
I'm not sure why, but GitHub failed to back-link from the other PR.

This is the bug fix in `osrf_testing_tools_cpp` for the variant issue: osrf/osrf_testing_tools_cpp#77

**Comment by clalancette** [comment]
I think I've now fixed all of the issues pointed out by @cottsay.  With the other fixes that are in place, let's see how CI does now:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19020/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13545/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19772/)

**Comment by clalancette** [comment]
All right, with https://github.com/ros2/rclcpp/pull/2227 now merged, I'm going to mark this PR as ready for review and run another CI on it.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19028/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13553/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19784/)

**Review by cottsay — APPROVED** [review]
I reviewed the diff and it aligns with my attempt to do the same.

Thanks!

**Comment by clalancette** [comment]
CI is green, and this is approved, so merging.  Note that I am going to create a merge commit here.

**Pull request merged**
